name: Docker Build & Push

on: [push]

jobs:
  build:
    runs-on: anh-self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Docker Build
        run: |
          docker build -t test_image:1.0.0 ./docker
      - name: Docker Push
        run: |
          docker tag test_image:1.0.0 anhmaciag/test_image:1.0.0
          docker push anhmaciag/test_image:1.0.0
      - name: Docker Check
        run: |
          echo Successfully Done!
          
